<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2qc0uf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2qc0uf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE2qc0uf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE2qc0uf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE2qc0uf\appProdProjectContainer([
    'container.build_hash' => 'E2qc0uf',
    'container.build_id' => '405b7040',
    'container.build_time' => 1589284965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2qc0uf');
