<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbxvawj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbxvawj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEbxvawj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEbxvawj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEbxvawj\appProdProjectContainer([
    'container.build_hash' => 'Ebxvawj',
    'container.build_id' => '1ab35bd5',
    'container.build_time' => 1589458900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbxvawj');
